---
title: "Consulting and Freelancing in Academia"
description: |
  A guide to getting started and doing well at consulting and freelancing, and avoiding some speed bumps. This is aimed squarely at people in academia who are good at working with data.
author:
  - name: Nick Huntington-Klein
    url: {https://www.nickchk.com}
date: 2021-11-19
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am an academic. I am very well suited to life in academia. I love every part of it, including teaching, and have very little interest in leaving it. This is true of my attitude and interests, and remains true despite the fact that I am unlikely to ever be published in a top journal in my field, and also that I have maintained, while in academia, a pretty lively string of consulting and freelancing assignments. 

In this post I will share with you some guidelines and tips for pursuing consulting and freelancing work while inside of academia, either as a grad student or as a professor. This will be targeted at people with a skillset similar to myself: people with lots of technical and analytic skill when it comes to working with data. It will also heavily suggest doing things in the exact way that I did them, and in the United States, because that's what I know. I will not pretend that this is the only way to do things. But it is one way.

I have decided that the most appropriate tone for a post like this is "world-weary" and I'll do what I can to rise to this standard.

## Why?

You're busy as heck. Why should you consider doing any sort of consulting?

- It pays you money. I have no complaints about my salary as a professor, not one, not ever. I hear professors complaining about how little they get paid and my mind explodes. I'd get it from, like, English professors maybe, but I'm talking business school people. I come from a background where the amount of money I make as a professor is stupid fantasy money. Just ridiculous. I look at the US income distribution and go "welp, I'm rich now I guess." In my first job out of grad school my annual salary was more than my parents at their highest-earning ever, combined. But professor salaries are indeed quite low compared to what that same skillset can earn you in the private sector, which to me is an even stupider, more fantastic amount of fantasy money. Many professors I know have a spouse with a similarly-remunerative job. Assortative mating. I support a three (soon to be four) person family in what I at least imagine to be an upper-middle-class lifestyle on a single income and without, like, a trust fund or whatever. Consulting makes that possible. **If you know how to work with data, your time is extraordinarily valuable, more than I can reasonably understand but apparently the market does. So get paid for it, at least sometimes.**
- Your academic job will usually be cool with it. Obviously check with them, etc., and take stuff into consideration like "can I use my school laptop for this work?" and "will it be a problem if I respond to client messages while on the university Wi-Fi?" and "is my proprietary software like Stata, Matlab, or Tableau licensed for commercial use or just academic use?" but there's a good chance nobody will get mad at you for taking consulting jobs.
- It provides interesting projects, occasionally. Most of the projects you'll work on as a freelancer will be pretty boring and basic. But occasionally you'll get forced into an arena you're not familiar with and will learn some cool new stuff. I've certainly been exposed to all kinds of interesting real-world detail in areas I wouldn't have bothered to look in before. Maybe the most interesting part to *you, the academic* isn't the same as the most interesting part to the *client*, but who cares, you're enjoying yourself. On extremely rare occasion your project will end up in a publication for you, too (I've done it once, with more on the way). 
- It develops your skills. Projects you get as a freelancer will often require you to use tools that are more common in business than in academia. Python, SQL, Excel, etc. It will also require you to think in different ways about what the goal of your work is (clean data, actionable takeaways, easy workflows rather than publishable insights or pristine research design). Sometimes this can lead to you being better-equipped for the next round of academic tech updates (who knows what language will be en vogue in 10 years?). Sometimes it will expose you to entire new fields (for example, the [Event Studies](https://theeffectbook.net/ch-EventStudies.html) chapter of my textbook was heavily informed by consulting jobs I'd been given in finance, a field I otherwise have very little interest in). This will also leave you more equipped for, well, working in the private sector (and better-connected! Two different clients have offered me full-time private sector jobs). Maybe that's what you want - if you're in grad school and are thinking about the private sector this is one way to build up some experience short of taking an actual job concurrent with your studies. Or maybe it's not what you want but you think you might end up there anyway. I'm in the US, and I think there's a non-ignorable chance that within the span of my career either the federal government, and maybe many states, will just sorta defund colleges and/or student aid massively, or that some new form of career prep will outcompete universities and demand will plummet. Where will that leave regional-university non-superstars like me? *Like* me? Dunno. *Me*? I'll be well-equipped to jump ship to some sort of tech company. I will miss academia, and the stage of society that supported it so much, dearly if it comes to that, but at no point will I miss eating. Or a mortgage payment for that matter.
- It provides immediate purpose. I rarely know if my academic research is having any real effect on the world at all. Even when it directly affects some sort of policy change I don't *really* know what change is being affected. But consulting work? Sure, maybe the end goal isn't quite as noble as improving humanity's stock of knowledge. But it improves *someone's* knowledge about something, and you can *see it work*. That's nice. Not to mention, my contracting work has led me to projects with actual academic-style noble-purpose outcomes. I've ended up in a number of projects that improved policy for nonprofits. I contributed to a governmental COVID task force, *which is a project I got through a for-profit client, not my academic work.* I've produced plenty of education materials on a contracting basis (in addition to the ones I make for free as public goods) and you can see those get used immediately.

That said, yes, this will eat into whatever free time you have, and you'll want to make sure you're doing well at your main academic job as a prerequisite for spending time on other stuff. Reviews at my academic job suggest I'm not skimping there. If that started to slip I'd reevaluate. 

In my case, it's definitely true that I work all the time and have had to largely excise everything but work and family from my life. But I'm okay with that. I say that not as a brag or judgment on how much people should work, but just an honest statement that I am pretty happy with a work/life balance the internet tells me I should not be happy with. I enjoy working. If you enjoy working less than I do then you should work less than I do. Consulting, conveniently, does let you scale how much work you're doing, as long as you're willing to say no when you have too much.

## How Should You Prepare?

- Do you know how to clean data from your academic experience?
- Do you know how to work with data and do the best analysis you can based on your academic experience?
- Can you explain your results in an extremely simplified way to someone who has never heard of a regression?
- Are you ready to accept that not all analyses need to be as careful as those heading for an academic publication, nor do they have the same goal as an academic publication, but that you need to find a way to be rigorous regardless? 

If so, you're good to go, at least conceptually. Technically you'll be doing yourself a favor if you're skilled in common private sector languages like Python and the various flavors of SQL (or, more importantly, can pick up new tools and languages on the fly). Or learning to do stuff without relying on fancy models. Or using Excel.

There are some parts of freelancing that have to do with changing the mindset you have around the work that you do (see the final point above). This is the kind of thing you'll just have to get through practice, though, so I won't bother trying to preview it.

## Where Can You Find Jobs?

I find jobs largely on [upWork](https://www.upwork.com/). There are other places with freelance job listings, too. If you can manage to get yourself hired directly by a company that needs someone on an ongoing basis and will pay you a decent rate, that's fantastic. I have, on occasion, built contacts through upWork that later turned into far more lucrative contracts direct with a company that has deep pockets.

You might wonder about the value of something like upWork given that they take a relatively hefty cut (20% for the first $500 with a client, 10% afterwards). But it's worth it. The platform provides a lot of clients. More than that, they make sure you get paid. If you work with someone one-on-one, who knows what happens. Wait a few months to get paid, never get paid, spend a lot of time chasing payment, etc.. upWork forces them to pay once you've agreed to something, I've had literally two contracts ever go south out of hundreds (and one of those went south in my favor, so hey!), and that's absolutely worth 10% on its own.

upWork isn't where I got started though, nor is it the only place I get work. I started out my freelancing focusing on education rather than data work. I did tutoring through Tutor.com and Chegg Tutors, I wrote a zillion practice questions for Albert.io, I wrote practice questions for textbook publishers. I generally don't advise this path for people situated in academia. This work is rote, time intensive, and poorly paid relative to working with data. Not to mention exposure to actual students in a freelance online-education setting means you'll spend the majority of your time dealing with people begging for you to just do their homework for them instead of getting paid (or giving in to those requests, and I hope you have more dignity than that). If you're a grad student and don't think you have the data chops yet, then sure. This stuff is at least low-commitment and can earn you a few bucks. 

Better opportunities outside of a job board like upWork often require connections of some sort, or being known for something. I've had a number of great opportunities come from being referred by a client I met on upWork to another client not on upWork. I've gotten hookups from friends who have gone into the private sector. I've also had companies email me to offer work. When you're a professor it happens! You might also come in contact with middlemen consulting agencies who link up freelancers with bigger companies. I've worked with a few such agencies, most of which hired me the first time off of upWork. All these experiences have been good. They have access to bigger clients that you'd be unlikely to find on your own. Good pay and longer-term projects.

Some of the most stressful and frustrating, but financially rewarding, work comes in the form of legal-case consulting. Remember the stupid fantasy money I mentioned in data work? Well, being an expert in a legal case, or just offering commentary and advice to one, is super-duper stupid fantasy money. If you've ever been on a jury for a trial with experts, you know lawyers love to ask the opposing experts what they get paid, and for good reason - what juror wants to listen to someone getting paid ludicrous amounts to be there? I've done two legal cases, one which came to me through upWork and one which was an email request, and each time charged several hundred dollars an hour. *This is low for what this usually pays.* 

You do have to put in the work, though. Lawyers expect extremely fast turnarounds, there are often restrictions on the scope of what questions you can answer or what methods you can use to answer them (if you've ever read an expert opinion for a legal case from an academic you like and thought "wow, this is not as good as their usual work," this is one reason why), and you might have to give deposition or testimony which can be a little terrifying. Plus, while this isn't something I've experienced myself, you might end up in a situation where the lawyers *really* want you to find a way to *make* their side right, rather than providing your actual best expertise, also then also put your name on it. The legal-case work I've done has all been in the form of rebuttal to other experts which makes some parts of this easier but not all of it.

On a much smaller scale, I will, as someone with a mildly public persona via [Twitter](https://twitter.com/nickchk) and [YouTube](https://www.youtube.com/channel/UCuSAKl6Q4JPA9O_cEFYEPGg), occasionally get requests straight to my email from individuals. Many of these are requests to help in general without pay (which I'm happy to oblige, up to a point), but others are offers of work. These might be worth it if you happen to have the time, but I don't think I've ever had one blossom into a truly worthwhile contract (see the note about "small contracts" below).

So how do you get work, in sum? At least starting out, if you don't have any connections your best bets are going to be a job board of some sort, or just waiting for the right opportunity to hit your inbox. It really does happen! 

## Getting Started

When you are starting out, you're probably going to be starting small unless you have some sort of hookup to a major project. This means building a good profile on a job board like upWork and accepting small jobs that you only expect to pay a few hundred dollars in total. At this point you can start working pretty quickly, but it's unlikely that you'll be making this whole venture really worthwhile right away, given the opportunity cost of your time. But you're building a profile with some hopefully satisfied clients, and getting used to how these consulting jobs work. 

At this point you're giving yourself a crash course in the parts of consulting that your academic and data skills *don't* cover. You're building negotiation skills and client-management skills. You'll want at least a little of that under your belt before taking any real big projects. Try to focus on taking projects where *your skills are handy* (i.e. sure you could proofread a college kid's essay for a few bucks but that's not really teaching you much in terms of building to something bigger), and that you can *turn around quickly.* Small projects with well-defined goals are great here. By doing these you'll be able to build a set of positive reviews (if you're on a job site) and a general knowledge of how this work operates without getting bogged down by any one project. You'll also get to know your own work habits and speed better. How long will that project *really* take you? Do you really have time to do it? You'll develop a much better internal sense of this.

Once you feel like you've got a handle on it you can go for bigger projects, and be more likely to land them because of your track record and improved ability to sell yourself to this audience. Bigger projects are generally better once you know how to handle them (see How Can You Deal with Clients below).

How much should you charge starting out? Don't undersell yourself. If you're on a job board, check what other people charge. You may be surprised. If you're just playing around and trying to get a few small contracts under your belt, sure, charge fifty bucks an hour or something. But once you're actually trying to earn money, or being asked to take on something that will actually compete for time with the rest of your busy schedule, you should charge what the market will bear! And the market will bear a fair amount. \$100/hour is a pretty low-end amount for an academic with data skills. I charge different clients between $90 (for long-time clients with consistent low-difficulty work) to \$150/hour (for new clients) these days, but I already get more offers than I can handle and so that $150 could probably be higher. Keep in mind that clients will often take too-low wages as an indicator of poor quality. Maybe it's just the upWork algorithm but whenever I raise my price I get flooded with new job requests. A high hourly rate will also deter people who do not actually want to pay you (see How Do You Deal with Clients? below).

Whatever hourly rate you land on, if you come to a project that pays for the final deliverable rather than hourly, you should think of that project in terms of how much time it will take you and charge based based on your hourly rate, plus a markup since you're taking the risk of the project requiring more time than you expect. You can even be explicit about it. I will often tell people asking for project-based payment "My hourly rate is \$$X$. I expect this will take $Y$ hours. So I will charge $X*(Y+Z)$ to cover the possibility that it will take longer. Or if you prefer, we can do an hourly rate, and maybe you won't need to pay for $Z$." 

One last thing - in the "figure this whole consulting thing out and get established" phase, since the projects you're taking are smaller you're likely to stumble upon some odder or more fun ones. Go for it, this is your time. You can definitely afford to cut your rate for someone offering you an evening of entertainment. This was the stage of my freelancing when I was definitely happy to write assignment guides or check someone's answers on their game theory homework, because I think game theory homework is fun and I miss being assigned it. This is the person you've chosen to read an article by and take advice from. (Note: when a student contacts you offering money to solve their homework or write their essay for them, obviously not something an academic should be doing, instead offer to write them an *assignment guide*, which includes no solutions but is a set of tips and nudges in the right direction to help them solve the assignment themselves. A surprising number of them will take you up on it).

## How Can You Deal with Clients?

Managing (and selecting) clients is a task that is really very different from something a typical academic is going to run into. Their expectations, desires, and ways in which they will take advantage of you are entirely different from the expectations, desires, and advantage-taking-ways of an advisor, boss, or purse-string-holder in academia.

### Which Clients Should You Avoid?

- Avoid any clients who are incapable of telling you what they want you to do. They will decide, after you have done it, that they actually wanted something else.
- Avoid anyone who wants to spend a lot of time negotiating the price with you or asks for a lot of discounts, especially if the project isn't that big anyway. Negotiating is fine but if it's more than one round of back-and-forth and the amounts you're negotiating over aren't enormous, start looking for the exit. Avoid these people for four reasons: (1) you don't get paid for that negotiating time and headache, (2) after they hire you they will likely be trying to find ways to stretch their dollar even further - asking for free extra little tasks, asking for partial refunds on pieces of the project that didn't go as planned, and (3) your time is valuable and scarce and thus expensive. If they don't want to pay your rate they they don't have to, but you aren't obliged to work for them. You can literally tell people who ask for big discounts that sorry, you know you're expensive, but that's how it is, there's probably someone else out there cheaper. I do that. People get it. Finally, (4) I can only speculate as to why, but every client who ever ended up *really* mistreating me - yelling at me, belittling me, trying to jump the bill, gaslighting me about what work I'd agreed to do, etc. - *every* single one started out as an exhaustive negotiation over nickels and dimes.
- Avoid anyone who wants to have a whole lot of scheduled phone or video calls with you to check up. Video calls aren't inherently a problem but I mean people who want constant progress check-ins in the form of calls, more than would actually be necessary for the project. Lots of expected calls should be a dealbreaker if they're not offering to pay for your time on the call. Run. If the contract being offered *is* such that you get paid for your call time (even if payment isn't hourly-rate, the calls should be listed as a part of the work you're getting paid for), then it's not a dealbreaker, but it's not great either. You're a busy academic. Consulting fits into the cracks in your schedule. I do the majority of my consulting work at night after the family is in bed. As soon as consulting work has to find a place *on* your regular work-hours schedule, it is consuming a much more valuable portion of your day.
- Avoid anyone who wants you to do bad work, at least most of the time. You'll get plenty of requests from people who have clearly decided what they want the data to show, and they want you to squeeze and squash the data until that happens. Or they want you to specifically use a method you know is garbage. Sometimes you can talk these people out of it - you're the expert after all. Explain why what they're asking you to do is a bad idea. But sometimes they still want it anyway. If it seems like the only one getting hurt by the bad analysis is them, well, it's their grave, it's up to you at that point if you want to help them in. But if the results are going to end up "informing" the public or affecting people, do the right thing and back out!

And finally, as time goes on, shift towards avoiding clients with small one-off projects more and more. There's nothing wrong with these, but new projects require setup, price negotiation, figuring out the goals, learning the ropes, etc.. You'll be using your time more effectively, and also have much more predictable responsibilities and income, with bigger projects. These bigger projects can run from month-long projects that pay 1-2 thousand dollars to multi-year engagements as the resident data consultant for a small company. So once you have enough big projects to fill your clock, avoid taking on small ones.

### Successfully Working with Clients

There are lots of things to consider when handling clients - being kind and prompt, returning work quickly, not letting them take advantage of you, and so on. But the most difficult and important part about working with clients, and what I'll focus on here, is handling their expectations. This includes what their expectations are of you and also what their expectations and desires are for the work you will give them. The reason this is so difficult is that private clients often have very different expectations and desires than you've been trained to think about in academia. So there's a minor culture shock.

That's your first goal, then. Figure out what it is they actually want. As a general rule, private clients are more interested in *results* than they are in *methods*. What are the takeaways? A reasonable data-driven hint as to what they should do is usually way more valuable to them than a caveat-filled conclusion that you're absolutely certain has been supported by the data and buttressed against any possible criticisms. 

With that in mind, you get a little bit of freedom to not be *quite* as rigorous as you would be in an academic setting. But this also means that you'll be doing a little dance of figuring out exactly where the line is between "result that's not quite as robust as something I'd try to publish in an academic journal" and "result I don't believe at all." 

This leads us back to handling client expectations. Letting them know what you can and can't do with the data that's been provided is key, and will help keep them from expecting more of the data than can actually be achieved.

Doing all of this properly requires understanding how clients think about the kind of work you do, a topic about which I had a [Twitter thread](https://twitter.com/nickchk/status/991397611306303488) long ago. Many private clients think of statistical analysis as a product they buy in a store that solves a problem for them, rather than as a tool for unconvering some sort of truth. 

This means that, at least initially, many of your clients will be expecting you to provide results that justifies a particular already-made choice, or looks good for them in some way, or provides a very clear and distinct answer to a super-important question. 

Obviously, results from data do not always fall this way. This can lead to problems. Clients will ask for a zillion variations until some result implies what they want (whether or not the result is mush by that point), they'll ask for a refund, or, worse, they'll string you along with revisions until something pops out that they like.

In my experience, the best salve here is to simply be honest. Remind clients that if they already had a conclusion in mind there'd be no need for data analysis. Tell them that, yes, in your expert opinion this really *is* what the data says. This approach doesn't always work, but it works sometimes, and I've yet to find a better alternative.

Letting clients know what they will, and will not, get from you is a pretty good idea in general. Yes, you can build a predictive model. No, you can't guarantee it will boost sales. 

There are a bunch of other skills that you'll learn in the process of doing consulting work that will help you manage clients better, but I've been thinking through them and for the life of me I can't think of any that I could adequately inform you about through text. So you'll just have to work past those issues yourself.

one thing I have left out, though, is managing academic clients. You'll actually get a lot of these, or at least I do. This makes sense - you're an academic. They need academic skills. Academic clients range from students wanting help with their assignments up to other academics basically hiring a postdoc but with lower commitment.

Academic clients can be great clients! But some things to keep in mind:

- If the client's a student, make extremely clear up front that you are helping them but aren't doing their assignment for them. 
- If the client's a professor, treat them like you treated whoever you may have RA'd for in grad school (if you did that) and you'll be golden. This isn't your project and you aren't a coauthor, do as you're told. That said, don't agree to coauthor with them unless you like the project and think you've contributed enough. I've been offered authorship on an *astonishing* number of papers that I did some very basic RA-level work on. I've always said no. Depending on your affiliation, this can sometimes be a very-transparent play to get a bad article in a bad journal instead of a very-bad journal. Not worth it coming up on a Google search of your name.
- Whoever the client is, there's sort of an expectation that, as an academic, this is the sort of thing you'd normally contribute to without pay. So the relationship can sometimes become less than business-like. But you can't help every struggling grad student or assistant professor in the world. Keep it professional, clients need to pay for your time.

That all said, academic clients can be great, and I will in many cases take lower payments for them. One aspect of freelancing I always enjoy is when grad students with *terrible* advisors come to me for help. I've never worked at a university with PhD students, but I've always wanted to be a dissertation advisor. This fills that lil' gap in my heart. I don't know where these grad students come up with the money to *pay* an advisor on an hourly basis (even at a discounted rate), but I've been the de-facto dissertation advisor to five students, four of whom ended up with PhDs (plus, served on the actual committee for a sixth, who for the record did not have an awful advisor and brought me in for coauthor-level work on their stats). Loved every minute of it. 

Also, five of you out there are just truly awful PhD advisors, and have your name as dissertation advisor on a student's CV when you didn't do jack, I did. I do know who you are.

## Managing Your Time

You're a busy person who already has a job. Consulting isn't going to work for you if you can't manage your time properly so it doesn't get in the way of your main job (or the rest of your life for that matter).

When thinking about how to manage your time, there are three big things to keep in mind. The first is in *taking on the right amount of work*, the second is in *taking the kind of work that gives you flexible scheduling*, and the third is in *avoiding project creep.*

*Taking on the right amount of work.* You should have a decent idea about the amount of time you have available to dedicate to consulting. Then, don't take on more work than will fill that time. This would be easy, except of course that hitting the sweet spot of how much work you'll take on can be very difficult.

This is not the most original of advice, but it's a good idea to look over a project carefully before committing to it, thinking about how long you expect it to take you, and then realizing that it will almost certainly take you longer than that. Pad your expected contribution, because you have no idea where surprises will lurk for you! This is important both for managing your time and in quoting prices to clients - anyone asking for an expected amount of time something will take you (if they're paying hourly) or a quote (for project-based payment) should get a number that is at the very least 20% above the time you actually think it will take you.

Taking on the right amount of work also means favoring projects where you have a better idea of where the endpoint is. Projects that change and expand as time goes on make it very difficult to manage your time (see *avoiding project creep* below).

*Pursuing flexible scheduling.* The easiest way to fit consulting work into a life that already has an academic job in it is to do work that can be done any time. This means avoiding work that requires lots of scheduled calls or that otherwise have to be done during business hours. 

This also means limiting the number of projects you have with very tight deadlines. Outside of grant-writing, deadlines for academic work are often suggestions - conference submission dates get pushed back, referee reports languish, the edit you told your coauthor would be done next week is, uh, well. There are plenty of hard deadlines in *academia*, university admin deadlines and so on, but not so much for *academic work*. If you need more time to do it right, then take more time until it's done right. Private clients do not  usually see things this way. If there's a deadline, you need to meet it. 

Tight deadlines do not give you flexibility, though. If I have a week to do a four-hour project, I can do 45 minutes a night and be done easy. If I have until tomorrow, well that's my day. Flexibility out the window! 

So unless it's a really good offer (like, say, a legal consulting gig), don't take projects that you'll have to crunch to finish. And if you have some control over the deadline, don't feel bad about pushing it out. Remember the padding for how many hours it will take you to do the project? Well, take that padded number and think about how many *days* it will take you to cobble together that much worktime. Then pad *that*. 

It does not feel good to have to push back working on a research project you're excited about because you gave a client a too-short deadline. So don't put yourself in that situation!

*Avoiding project creep.* Certain projects have ways of *expanding* as they go along. Sometimes this is fine. Projects that go well get sequels, so to speak, and if it's work you like, and you can plan ahead for those sequels, then great! That's just a return customer. But some projects expand in bad ways that can leave you frustrated and eternally unable to bid farewell to the project. Unfortunately it can be tricky to catch these up front a lot of the time, but there are warning signs.

One major warning sign is if you are going to be working with data that you can tell is super noisy or just isn't very good, or are being asked to use bad methods. Data analysis works to some degree on a garbage-in-garbage-out principle. In my experience, clients are very willing to push back on "garbage-out," and will tell you that results aren't plausible and need to be fixed (good instincts born of deep contextual knowledge!), but they will often fail to accept "garbage-in" as an explanation (bad instincts born of a lack of data-analytic intuition). Thus begins the project creep where you are asked to try an ever-expanding list of alternate methods so as to find the one magic configuration that produces a believable result. All the while the entire project annoys you because you know the work you're doing is very, very bad. Plus, if you agreed to project-based payment, you'll quickly hit the point where the project is no longer a good deal for you, but the marginal cost of *just one more variant* is low enough that you keep just hoping it will end and they'll pay up. Worst-case scenario is they try not to pay because they don't like the result.

You can avoid some of this by building a maximum number of revisions into your project-based contract. This is harder to squirm out of if you're on an hourly contract though. What you should really do is do a very careful assessment of whether the data is likely to produce anything believable, and back out if it's not up to the task. You can try saying something to the client ahead of time like "hey I'll run this if you want. It will probably be garbage though," but almost every time I've done that they've said to go ahead anyway and the same cycle has occurred.

On bigger projects where you're a consultant working with a team, you can avoid some of this project creep by being sure to talk extensively about the data *directly with the person who knows the most about it.* The number of projects I've had to redo because the middleman between the data person and me didn't explain something properly and I had to redo everything at the last second!

As an aside, you will also often find it worthwhile to *anticipate project creep* before it happens, and prepare yourself for it. The only advice I really have to this end is to always write your code in a way that's easy to expand upon. Private clients, just like Twitter commenters, *love* to look at your final result and say "neat, but how about you look at that same result in these twenty different subcategories?" At that point you'll be kicking yourself if you haven't already written your code in such a way that you can just loop over it to get results by subcategory.

## Don't Forget Taxes

This section is completely US-centric. It seems important for this section to point out that I'm not an accountant and this is not, like, professional tax advice or anything. So, really, double-check everything I'm telling you against an official source. My only credentials are that I have been doing my own taxes a long time and know my way around this stuff pretty well. 

Consulting income is indeed income. If you've only ever worked, like, actual jobs before with W-2s and such it can be easy to forget that that one-time project you did in May that paid like $800 is also income that you have to pay taxes on. In fact, there are a few things that might change about the way you do taxes if you start doing substantial amounts of consulting. For one, you might not be paying taxes just once a year any more (so if you start getting real into consulting, don't think you can just wait until April and tack on an amount and see what happens, you may be in for some late fees).

Things to note, especially if you are doing your own taxes:

- You won't get W-2's for your consulting work, so don't wait around for them to come, or think that you don't have to report the income because you didn't get a W-2.. For bigger clients (or job boards like upWork) you'll likely get a 1099. But even if it's for a smaller client not on a job board, you'll still need to report the income. So keep track of it!
- As soon as you start doing consulting work. you're a business! A sole proprietorship. That doesn't mean you have to do the whole rigamarole of filing business taxes and registering as a business, though. For the most part, if you want you can just keep doing your regular ol' individual-person taxes, and there are just a few additional forms to add with places to put your non-regular-job income.
- Your typical paycheck from a job will helpfully withhold taxes for you so you don't need to think about it. No longer! You need to withhold your own taxes. Figure out ahead of time what your tax rate is (which includes income taxes and some other stuff I'll talk about here), and set aside that portion of all your consulting income. Further, you need to *send* those withheld funds into the IRS four times a year. See [Form 1040ES](https://www.irs.gov/pub/irs-pdf/f1040es.pdf). If your state has income taxes it will likely have a similar process.
- You'll need to report this income on a Schedule C form (and then also Schedule 1) when doing your 1040.
- On that Schedule C is a spot to report business expenses. Yep, you have business expenses now! This is not the same as your regular-ol' 1040 itemized-or-standard deduction for personal income. Business expenses are counted directly against your business income. Make sure only to report stuff that you *only* use for your consulting. Buy a laptop for both your consulting work *and* your academic job? Not a deduction. But run an AWS server for your clients? Bought a Tableau license for your consulting? Deduct it. There are even ways to deduct part of your rent/mortgage if you have a room in your home that is *only* used as your office for consulting work. 
- You don't just need to withhold income tax. Payroll taxes apply to consulting income, too. Plus, payroll taxes are split between employer and employee. You're both now! So you'll be paying both sides (although one of those sides is itself tax-deductible). Fun. File a Schedule SE ("self-employment tax").
- On the flip side, check out the qualified business income deduction! You qualify for that now (or at least I do). Sweet, eh?
- If you start doing a *lot* of consulting and plan to keep it that way, you might consider setting up an S-corp (pass-through corporation). This can reduce your payroll tax burden (as some portion of your consulting income comes due to you as owner of the S-corp rather than to you as someone who works in the S-corp) and also changes some other stuff. You'll have to pay to incorporate, which is a downside, and you'll have to start filing quarterly 941 forms and also annual business taxes (including unemployment on a 940). Oh yeah and the filing months for the quarterly 941 forms don't line up exactly with the quarterly 1040ES forms for some reason. Your taxes will get complex enough at this point that you'll definitely want to pay an accountant to do them for you, which will likely cost a couple thousand, at least for the first year (after which point you can crib off their work if you want). I have an S-corp and I'm not yet sure if it has turned out to be a good idea. A year and a half into it and I have *maybe* saved enough taxes to offset the setup costs. Maybe.
- Tax rules are very complex to figure out, but tax *forms* are pretty simple little homework assignments. I strongly recommend making an Excel workbook that does the math of the 1040 and all its sub-forms for you, and also has a place for you to enter all the payments you've received (which feeds straight into the appropriate 1040 cells). This is not very much work to set up, and once you're done you sort of have your own lil TurboTax. Benefits include: (1) your taxes are already done when it comes time to file taxes, (2) you definitely want to keep good books now that you're doing your own. The part of this process where you set up a spot to record all the times you get paid means you're now keeping good books. And (3) assuming you've also included the 1040ES worksheet in there, which you should, and also a place to put in all your actual W-2 income with witholding and stuff, you'll know exactly how much you need to mail in when it's quarterly-taxes time.

## And So

Consulting! Freelancing! Try it out. If you have the time, sign up for upWork and do a few jobs, see if you like it. You may get a lot of interesting and educational experiences from it, too, in addition to being paid. It doesn't even have to become an enormous part of what you do, since you can largely set your own limits on how much you work. I've found it pretty rewarding in many ways, and hopefully this article can help you avoid some of the headaches I ran into.

Don't do more of it than you want to. But also don't do less of it than you want to. Do the correct amount of it. This is useful advice.

